routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'UserChartController@index')->name('home')->middleware('auth');


Route::group(['middleware' => 'auth'], function () {
		Route::get('tables', ['as' => 'pages.tables', 'uses' => 'PageController@tables']);
		Route::get('try', ['as' => 'pages.try', 'uses' => 'PageController@try']);
		
		Route::get('subjectIndex', ['as' => 'pages.subjectIndex', 'uses' => 'SubjectController@subjectIndex']);
		Route::get('createSubject/{id}', ['as' => 'createSubject', 'uses' => 'SubjectController@create']);
		Route::post('storeSubject', ['as' => 'storeSubject', 'uses' => 'SubjectController@store']);
		Route::get('editsubject/{id}', ['as' => 'editsubject', 'uses' => 'SubjectController@edit']);
		Route::get('subjectStatus/{id}', ['as' => 'subjectStatus', 'uses' => 'SubjectController@subjectStatus']);
		Route::put('updateSubject/{id}', ['as' => 'updateSubject', 'uses' => 'SubjectController@updateSubject']);
		Route::DELETE('deleteSubject/{id}', ['as' => 'deleteSubject', 'uses' => 'SubjectController@destroy']);

		Route::get('meetingsIndex', ['as' => 'meetingsIndex', 'uses' => 'MeetingController@index']);
		Route::get('create', ['as' => 'createMeeting', 'uses' => 'MeetingController@create']);
		Route::put('update/{id}', ['as' => 'updateMeeting', 'uses' => 'MeetingController@update']);
		Route::post('store', ['as' => 'storeMeeting', 'uses' => 'MeetingController@store']);
		Route::get('edit/{id}', ['as' => 'editMeeting', 'uses' => 'MeetingController@editMeeting']);
		Route::get('show/{id}', ['as' => 'showMeeting', 'uses' => 'MeetingController@show']);
		Route::DELETE('delete/{id}', ['as' => 'deleteMeeting', 'uses' => 'MeetingController@destroy']);
		Route::get('trashedMeeting', ['as' => 'trashedMeeting', 'uses' => 'MeetingController@trashed']);
		Route::put('restoreMeeting/{id}', ['as' => 'restoreMeeting', 'uses' => 'MeetingController@restore']);
		Route::get('attended/{id}/{meetingId}', ['as' => 'attended', 'uses' => 'MeetingController@attended']);
		Route::get('closeMeeting/{meetingId}', ['as' => 'closeMeeting', 'uses' => 'MeetingController@closeMeeting']);
		
		Route::get('tasksIndex', ['as' => 'tasksIndex', 'uses' => 'TaskController@index']);
		Route::get('createTask/{id}', ['as' => 'createTask', 'uses' => 'TaskController@create']);
		Route::get('editTask/{id}', ['as' => 'editTask', 'uses' => 'TaskController@edit']);
		Route::get('showTask/{id}', ['as' => 'showTask', 'uses' => 'TaskController@show']);
		Route::post('storeTask/{id}', ['as' => 'storeTask', 'uses' => 'TaskController@store']);
		Route::put('updateTask/{task_id}', ['as' => 'updateTask', 'uses' => 'TaskController@update']);
		Route::get('taskStatus/{task_id}', ['as' => 'taskStatus', 'uses' => 'TaskController@taskStatus']);
		Route::DELETE('deleteTask/{id}', ['as' => 'deleteTask', 'uses' => 'TaskController@destroy']);
		Route::get('trashedTask', ['as' => 'trashedTask', 'uses' => 'TaskController@trashed']);
		Route::put('restore/{id}', ['as' => 'restore', 'uses' => 'TaskController@restore']);

		Route::get('homeMail', ['as' => 'mail', 'uses' => 'MailController@home']);
		Route::post('send/email', 'MailController@sendemail');
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show','create','store']]);
	Route::get('invite', ['as' => 'invite', 'uses' => 'UserController@invite']);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::get('try', ['as' => 'pages.try', 'uses' => 'UserChartController@index']);
});

Route::get('userAdd', ['as' => 'addUser', 'uses' => 'UserController@create']);
Route::post('userStore', ['as' => 'userStore', 'uses' => 'UserController@store']);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','phone','organization_id','role','bio'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function organization(){
        return $this->belongsTo('App\Organization');

    }

   public function meetings(){

        return $this->belongsToMany('App\Meeting');

    }

    public function tasks(){
        return $this->hasMany('App\Task');

    }

    public function role(){
        return $this->blongsTo('App\Role');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Role;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Http\Requests\StoreUserRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the users
     *
     * @param  \App\User  $model
     * @return \Illuminate\View\View
     */
    public function index(User $model)
    {
        $id = Auth::id();
        $atuh_user = User::findOrFail($id);
        $roles = Role::all();
        $model = $atuh_user->where('organization_id',$atuh_user->organization_id)->get();
        return view('users.index', ['users' => $model])->with('roles', $roles);
    }

    /**
     * Show the form for creating a new user
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $users = User::all()->whereIn('role',['CEO', 'executive_manager']);
        return view('users.create')->with('users',$users);
    }

    /**
     * Store a newly created user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $request)
    {
        $model = new User();
        $model->name=$request->name;
        $model->email=$request->email;
        $model->phone=$request->phone;
        $model->organization_id=$request->organization;
        $model->role = 'employee';
        $model->password=Hash::make($request->get('password'));
        
        $model->save();
        return redirect()->route('login')->withStatus(__('User successfully created.'));
    }

    /**
     * Show the form for editing the specified user
     *
     * @param  \App\User  $user
     * @return \Illuminate\View\View
     */
    public function edit(User $user)
    {   
       
        $roles = Role::all();
        $auth = Auth::id();
        $current = User::findOrFail($auth);

        if ($user->id == 1) {
            return redirect()->route('user.index');
        }

        return view('users.edit')->with('user', $user)->with('roles', $roles)->with('current', $current);
    }

    /**
     * Update the specified user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UserRequest $request, User  $user)
    {
        $user->update(
            $request->merge(['password' => Hash::make($request->get('password'))])
                ->except([$request->get('password') ? '' : 'password'])
            );
        $user->role = $request->roles;
        $user->update();

        return redirect()->route('user.index')->withStatus(__('User successfully updated.'));
    }

    /**
     * Remove the specified user from storage
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(User  $user)
    {
        if ($user->id == 1) {
            return abort(403);
        }

        $user->delete();

        return redirect()->route('user.index')->withStatus(__('User successfully deleted.'));
    }

    public function invite(){
        $id = Auth::id();
        $user = User::findOrFail($id)->firstOrFail();
        // dd($user->email);
        return view('users.invite')->with('user', $user);

    }

}

resources/views/users/create.blade.php
@extends('layouts.app', ['page' => __('User Management'), 'pageSlug' => 'users'])

@section('content')
    <div class="container-fluid mt--7" style="font-family: 'Lobster', cursive;">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">User Management</h3>
                            </div>
                          
                        </div>
                    </div>
                   
                    <div class="card-body">
                        <form method="post" action="{{ route('userStore') }}" autocomplete="off">
                            @csrf

                            <h6 class="heading-small text-muted mb-4">User information</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">Name</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Name" value="{{ old('name') }}" required autofocus>
                                    @include('alerts.feedback', ['field' => 'name'])
                                </div>
                                <div class="form-group{{ $errors->has('Phone') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">Phone</label>
                                    <input type="phone" name="phone" id="input-name" class="form-control form-control-alternative{{ $errors->has('Phone') ? ' is-invalid' : '' }}" placeholder="Phone" value="{{ old('Phone') }}" required autofocus>
                                    @include('alerts.feedback', ['field' => 'Phone'])
                                </div>
                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-email">Email</label>
                                    <input type="email" name="email" id="input-email" class="form-control form-control-alternative{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="Email" value="{{ old('email') }}" required>
                                    @include('alerts.feedback', ['field' => 'email'])
                                </div>
                                <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-password">Password</label>
                                    <input type="password" name="password" id="input-password" class="form-control form-control-alternative{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="Password" value="" required>
                                    @include('alerts.feedback', ['field' => 'password'])
                                </div>
                                <div class="form-group">
                                    <label class="form-control-label" for="input-password-confirmation">Confirm Password</label>
                                    <input type="password" name="password_confirmation" id="input-password-confirmation" class="form-control form-control-alternative" placeholder="Confirm Password" value="" required>
                                </div>

                                <div class="form-group">
                                    <label for="organization">How invited you?</label>
                                        <select name="organization" class="form-control" style="background-color: #222a42">
                                            @foreach($users as $user)
                                                <option value="{{ $user->organization_id}} ">
                                                    {{ $user->email}}
                                                </option>
                                            @endforeach
                                        </select>
                                        @include('alerts.feedback', ['field' => 'password'])
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app', ['page' => __('User Management'), 'pageSlug' => 'users'])

@section('content')
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">User Management</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary">Back to list</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('user.update', $user) }}" autocomplete="off">
                            @csrf
                            @method('put')

                            <h6 class="heading-small text-muted mb-4">User information</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">Name</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Name" value="{{ old('name', $user->name) }}" required autofocus>
                                    @include('alerts.feedback', ['field' => 'name'])
                                </div>
                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-email">Email</label>
                                    <input type="email" name="email" id="input-email" class="form-control form-control-alternative{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="Email" value="{{ old('email', $user->email) }}" required>
                                    @include('alerts.feedback', ['field' => 'email'])
                                </div>
                                <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-password">Password</label>
                                    <input type="password" name="password" id="input-password" class="form-control form-control-alternative{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="Password" value="">
                                    @include('alerts.feedback', ['field' => 'password'])
                                </div>
                                <div class="form-group">
                                    <label class="form-control-label" for="input-password-confirmation">Confirm Password</label>
                                    <input type="password" name="password_confirmation" id="input-password-confirmation" class="form-control form-control-alternative" placeholder="Confirm Password" value="">
                                </div>
                                @if($current->role == 'CEO')
                                <div class="form-group{{ $errors->has('role') ? ' has-danger' : '' }}">
                                <label>Role</label>
                                <select name="roles" class="form-control">
                                    @foreach($roles as $role)
                                        <option value="{{ $role->role_name}}" style="color:black">
                                            {{ $role->role_name }}
                                        </option>
                                    @endforeach
                                </select>
                                    
                                @include('alerts.feedback', ['field' => 'role'])
                                </div>
                                @endif
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app', ['page' => __('User Management'), 'pageSlug' => 'users'])

@section('content')

    <div class="row" >
        <div class="ml-5 my-5">
            <div class="card ">
                <div class="card-header">
                    <div class="row">
                        <div class="col-8">
                            <h1 class="card-title my-3" style="font-family: 'Lobster', cursive;">All employees <i class="fab fa-laravel text-info"></i></h1>
                        </div>
                        @if(Auth::user()->role == 'CEO' || Auth::user()->role == 'executive_manager')
                        <div class="col-4 text-right">
                            <a href="{{ route('invite') }}" class="btn btn-sm btn-success">Invite user<i class="tim-icons icon-send ml-2"></i></a>
                        </div>
                        @endif
                    </div>
                </div>
                <div class="card-body">
                    @include('alerts.success')

                    
                        <table class="table tablesorter" id="">
                            <thead class=" text-primary">
                                <th scope="col">Name</th>
                                <th scope="col">Email</th>
                                <th scope="col">Phone</th>
                                <th scope="col">Role</th>
                                <th scope="col">Creation Date</th>
                                <th scope="col"></th>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                    <tr style="font-family: 'Lobster', cursive;">
                                        <td>{{ $user->name }}</td>
                                        <td>
                                            <a class="text-info" href="mailto:{{ $user->email }}">{{ $user->email }}</a>
                                        </td>
                                        <td>{{$user->phone}}</td>
                                        
                                        <td><div class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                    @if($user->role == 'CEO')
                                                    <p class="text-warning">{{$user->role}}</p>
                                                    @elseif($user->role == 'executive_manager')
                                                    <p class="text-success">{{$user->role}}</p>
                                                    @elseif($user->role == 'vp_coordinator')
                                                    <p class="text-primary">{{$user->role}}</p>
                                                    @elseif($user->role == 'employee')
                                                    <p style="color:white !important">{{$user->role}}</p>
                                                    @endif
                                            </a>
                                            </div>
                                        </td>
                                        <td>{{ $user->created_at->format('d-m-Y H:i') }}</td>                                      
                                       @if(Auth::user()->role == 'CEO' || Auth::user()->role == 'executive_manager')
                                        <td class="text-right">
                                                <div class="dropdown">
                                                    <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        <i class="fas fa-ellipsis-v"></i>
                                                    </a>
                                                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                        @if (auth()->user()->id != $user->id)
                                                            <form action="{{ route('user.destroy', $user) }}" method="post">
                                                                @csrf
                                                                @method('delete')

                                                                <a class="dropdown-item" href="{{ route('user.edit', $user) }}">Edit</a>
                                                                <button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this user?") }}') ? this.parentElement.submit() : ''">
                                                                            Delete
                                                                </button>
                                                            </form>
                                                        @else
                                                            <a class="dropdown-item" href="{{ route('profile.edit') }}">Edit</a>
                                                        @endif
                                                    </div>
                                                </div>
                                        </td>
                                        @endif
                                        
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                   
                </div>
                <div class="card-footer py-4">
                    <nav class="d-flex justify-content-end" aria-label="...">
                       
                    </nav>
                </div>
            </div>
        </div>
    </div>
  
@endsection

resources/views/users/invite.blade.php
@extends('layouts.app', ['page' => __('User Management'), 'pageSlug' => 'users'])

@section('content')
<div class="container" style="font-family: 'Lobster', cursive;">
    <div class="row justify-content-center my-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header"><h4 class="pb-3 my-3" style="text-align:center; font-weight:bold">Invite Employee</h4></div>

                <div class="card-body">
                    <form method="POST" action="{{url('send/email')}}">
                        @csrf

                        <div class="form-group row">
                            <label for="subject" class="col-md-4 col-form-label text-md-right" style="color:white; font-weight:bold">Subject</label>

                            <div class="col-md-6">
                                <input id="subject" name="subject" type="text" class="form-control @error('subject') is-invalid @enderror" name="subject" value="{{ old('subject') }}" 
                                required autocomplete="subject" autofocus>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right" style="color:white; font-weight:bold">Email</label>

                            <div class="col-md-6">
                                <input id="email" name="email" type="email" class="form-control @error('email') is-invalid @enderror" name="subject" value="{{ old('subject') }}" 
                                required autocomplete="email" autofocus>
                            </div>
                        </div>

                        <div class="form-group row">
 
                            <div class="col-md-6">
                                <textarea name="message" id="" cols="5" rows="3" hidden>
                                    {{URL::signedRoute('addUser')}}
                                    
                                    you are invited by {{Auth::user()->email}}
                                </textarea>
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-warning">Send Email</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection