routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'UserChartController@index')->name('home')->middleware('auth');


Route::group(['middleware' => 'auth'], function () {
		Route::get('tables', ['as' => 'pages.tables', 'uses' => 'PageController@tables']);
		Route::get('try', ['as' => 'pages.try', 'uses' => 'PageController@try']);
		
		Route::get('subjectIndex', ['as' => 'pages.subjectIndex', 'uses' => 'SubjectController@subjectIndex']);
		Route::get('createSubject/{id}', ['as' => 'createSubject', 'uses' => 'SubjectController@create']);
		Route::post('storeSubject', ['as' => 'storeSubject', 'uses' => 'SubjectController@store']);
		Route::get('editsubject/{id}', ['as' => 'editsubject', 'uses' => 'SubjectController@edit']);
		Route::get('subjectStatus/{id}', ['as' => 'subjectStatus', 'uses' => 'SubjectController@subjectStatus']);
		Route::put('updateSubject/{id}', ['as' => 'updateSubject', 'uses' => 'SubjectController@updateSubject']);
		Route::DELETE('deleteSubject/{id}', ['as' => 'deleteSubject', 'uses' => 'SubjectController@destroy']);

		Route::get('meetingsIndex', ['as' => 'meetingsIndex', 'uses' => 'MeetingController@index']);
		Route::get('create', ['as' => 'createMeeting', 'uses' => 'MeetingController@create']);
		Route::put('update/{id}', ['as' => 'updateMeeting', 'uses' => 'MeetingController@update']);
		Route::post('store', ['as' => 'storeMeeting', 'uses' => 'MeetingController@store']);
		Route::get('edit/{id}', ['as' => 'editMeeting', 'uses' => 'MeetingController@editMeeting']);
		Route::get('show/{id}', ['as' => 'showMeeting', 'uses' => 'MeetingController@show']);
		Route::DELETE('delete/{id}', ['as' => 'deleteMeeting', 'uses' => 'MeetingController@destroy']);
		Route::get('trashedMeeting', ['as' => 'trashedMeeting', 'uses' => 'MeetingController@trashed']);
		Route::put('restoreMeeting/{id}', ['as' => 'restoreMeeting', 'uses' => 'MeetingController@restore']);
		Route::get('attended/{id}/{meetingId}', ['as' => 'attended', 'uses' => 'MeetingController@attended']);
		Route::get('closeMeeting/{meetingId}', ['as' => 'closeMeeting', 'uses' => 'MeetingController@closeMeeting']);
		
		Route::get('tasksIndex', ['as' => 'tasksIndex', 'uses' => 'TaskController@index']);
		Route::get('createTask/{id}', ['as' => 'createTask', 'uses' => 'TaskController@create']);
		Route::get('editTask/{id}', ['as' => 'editTask', 'uses' => 'TaskController@edit']);
		Route::get('showTask/{id}', ['as' => 'showTask', 'uses' => 'TaskController@show']);
		Route::post('storeTask/{id}', ['as' => 'storeTask', 'uses' => 'TaskController@store']);
		Route::put('updateTask/{task_id}', ['as' => 'updateTask', 'uses' => 'TaskController@update']);
		Route::get('taskStatus/{task_id}', ['as' => 'taskStatus', 'uses' => 'TaskController@taskStatus']);
		Route::DELETE('deleteTask/{id}', ['as' => 'deleteTask', 'uses' => 'TaskController@destroy']);
		Route::get('trashedTask', ['as' => 'trashedTask', 'uses' => 'TaskController@trashed']);
		Route::put('restore/{id}', ['as' => 'restore', 'uses' => 'TaskController@restore']);

		Route::get('homeMail', ['as' => 'mail', 'uses' => 'MailController@home']);
		Route::post('send/email', 'MailController@sendemail');
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show','create','store']]);
	Route::get('invite', ['as' => 'invite', 'uses' => 'UserController@invite']);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::get('try', ['as' => 'pages.try', 'uses' => 'UserChartController@index']);
});

Route::get('userAdd', ['as' => 'addUser', 'uses' => 'UserController@create']);
Route::post('userStore', ['as' => 'userStore', 'uses' => 'UserController@store']);

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth

@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar">
    <div class="sidebar-wrapper">
        <div class="logo">
            <a href="#" class="simple-text logo-normal" style="text-align:center">www.Unificient.com</a>
        </div>
        <ul class="nav">
            <li @if ($pageSlug == 'dashboard') class="active" @endif>
                <a href="{{ route('pages.try') }}">
                    <i class="tim-icons icon-chart-pie-36"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li>
                <a data-toggle="collapse" href="#organization_users" aria-expanded="true">
                    <i class="fab fa-laravel" ></i>
                    <span class="nav-link-text" >Employee Management</span>
                    <b class="caret mt-1"></b>
                </a>

                <div class="collapse" id="organization_users">
                    <ul class="nav pl-4">
                        <li @if ($pageSlug == 'profile') class="active " @endif>
                            <a href="{{ route('profile.edit')  }}">
                                <i class="tim-icons icon-single-02"></i>
                                <p>My Profile</p>
                            </a>
                        </li>
                        <li @if ($pageSlug == 'users') class="active " @endif>
                            <a href="{{ route('user.index')  }}">
                                <i class="tim-icons icon-bullet-list-67"></i>
                                <p>Employee index</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                <a data-toggle="collapse" href="#meetings" aria-expanded="true">
                <i class="tim-icons icon-calendar-60" ></i>
                    <span class="nav-link-text" >Meetings</span>
                    <b class="caret mt-1"></b>
                </a>

                <div class="collapse" id="meetings">
                    <ul class="nav pl-4">
                        <li @if ($pageSlug == 'meetingsIndex') class="active " @endif>
                            <a href="{{ route('meetingsIndex') }}">
                                <i class="fab fa-linode"></i>
                                <p>Meetings Index</p>
                            </a>
                        </li>
                        @if(Auth::user()->role != 'employee')
                        <li @if ($pageSlug == 'createMeeting') class="active " @endif>
                            <a href="{{ route('createMeeting') }}">
                                <i class="fab fa-mixcloud"></i>
                                <p>create Meeting</p>
                            </a>
                        </li>
                        @endif
                    </ul>
                </div>
            </li>
            <li>
                        <li @if ($pageSlug == 'tasksIndex') class="active " @endif>
                            <a href="{{ route('tasksIndex') }}">
                            <i class="tim-icons icon-notes" ></i>
                                <p>Tasks Index</p>
                            </a>
                        </li>
            </li>
            <li>
                <a data-toggle="collapse" href="#trash" aria-expanded="true">
                    <i class="tim-icons icon-trash-simple" ></i>
                    <span class="nav-link-text" >Trash</span>
                    <b class="caret mt-1"></b>
                </a>

                <div class="collapse" id="trash">
                    <ul class="nav pl-4">
                        <li @if ($pageSlug == 'trashMeetings') class="active " @endif>
                            <a href="{{ route('trashedMeeting') }}">
                            <i class="tim-icons icon-calendar-60" ></i>
                                <p>Trashed meetings</p>
                            </a>
                        </li>
                        <li @if ($pageSlug == 'trashTasks') class="active " @endif>
                            <a href="trashedTask">
                            <i class="tim-icons icon-notes" ></i>
                                <p>Trashed tasks</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</div>